from pydantic import BaseModel, Field
from typing import Literal, Annotated
from operator import add



class Agent(BaseModel):
    messages: Annotated[list,add] = Field(description="List of messages to be processed by the agent")
    curated_ques: str = Field(description="Curated question for the agent to answer")
    prompt_query_context: str = Field(description=" detailed prompt with SQL DB context that will help agent to generate SQL Query")
    is_safe: Literal[True] = Field(description="Indicates whether the generated SQL Query is safe to execute or not")
    sql_query: str = Field(description="SQL Query generated by the agent based on the curated question and prompt query context")
    sql_query_result: str = Field(description="Result of executing the SQL Query generated by the agent")
    final_answer: str = Field(description="Final answer generated by the agent based on the SQL Query result and curated question")
    schema_details: str = Field(description="Details of the database schema, including table names, column names, data types, and sample data")