from pydantic import BaseModel, Field
from typing import Literal




class AgentSchema(BaseModel):
    messages: list = Field(
        default_factory=list,
        description="List of messages to be processed by the agent",
    )
    user_query: str = Field(
        default="",
        description="User's original query that needs to be answered by the agent",
    )
    curated_ques: str = Field(
        default="",
        description="Curated question for the agent to answer",
    )
    prompt_query_context: str = Field(
        default="",
        description="Detailed prompt with SQL DB context that will help agent to generate SQL Query",
    )
    is_safe: Literal["Yes", "No"] = Field(
        default="No",
        description="Indicates whether the generated SQL Query is safe to execute or not",
    )
    comments: str = Field(
        default="",
        description="Comments or feedback provided by the agent regarding the safety of the SQL Query",
    )
    generated_sql_query: str = Field(
        default="",
        description="SQL Query generated by the agent based on the curated question and prompt query context",
    )
    sql_query_result: str = Field(
        default="",
        description="Result of executing the SQL Query generated by the agent",
    )
    final_answer: str = Field(
        default="",
        description="Final answer generated by the agent based on the SQL Query result and curated question",
    )
    schema_details: str = Field(
        default="",
        description="Tell which schema details are used by the agent to generate SQL Query and final answer",
    )


class JudgeSchema(BaseModel):
    is_safe: Literal["Yes", "No"] = Field(description="Indicates whether the generated SQL Query is safe to execute or not")
    comments: str = Field(description="Comments or feedback provided by the agent regarding the safety of the SQL Query")


class ETLAgentSchema(BaseModel):
    messages: list = Field(
        default_factory=list,
        description="List of messages to be processed by the agent",
    )


class RouterSchema(BaseModel):
    answer: Literal["sql", "etl"] = Field(description="Indicates whether the agent is a SQL agent or an ETL agent")
    comments: str = Field(description="Comments or feedback provided by the agent regarding the routing decision")


class DataAgentSchema(BaseModel):
    messages: list = Field(
        default_factory=list,
        description="List of messages to be processed by the agent",
    )
    router_response: Literal["sql", "etl"] | None = Field(default=None,description="Response from the router agent indicating whether to route to SQL or ETL agent")